[package]
name         = "argus-proto"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
publish.workspace      = true
repository.workspace   = true

[dependencies]
argus-core.path      = "../argus-core"
argus-crypto.path    = "../argus-crypto"
serde.workspace      = true
serde_json.workspace = true
base64ct.workspace   = true
thiserror.workspace  = true
webauthn-rs.workspace = true
url.workspace        = true
uuid.workspace       = true

[lints]
workspace = true
