[package]
name         = "argus"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
publish.workspace      = true
repository.workspace   = true

[dependencies]
argus-core.path   = "../argus-core"
argus-sandbox.path = "../argus-sandbox"
argus-crypto.path = "../argus-crypto"
aws-lc-rs.workspace = true
argus-proto.path  = "../argus-proto"
argus-saml.path      = "../argus-saml"
argus-ldap.path      = "../argus-ldap"
argus-http.path   = "../argus-http"
argus-store.path  = "../argus-store"
sqlx.workspace    = true
axum.workspace    = true
tokio.workspace   = true
uuid.workspace    = true
rustls.workspace         = true
tokio-rustls.workspace   = true
hyper.workspace          = true
hyper-util.workspace     = true
webpki-roots.workspace   = true

[lints]
workspace = true
