[package]
name         = "argus"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[dependencies]
argus-core.path   = "../argus-core"
argus-crypto.path = "../argus-crypto"
argus-proto.path  = "../argus-proto"
argus-http.path   = "../argus-http"
axum.workspace    = true
tokio.workspace   = true
uuid.workspace    = true

[lints]
workspace = true
