[package]
name         = "argus-crypto"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[dependencies]
argus-core.path     = "../argus-core"
aws-lc-rs.workspace = true
thiserror.workspace = true

[lints.rust]
unreachable_pub = "warn"

[lints.clippy]
all      = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
panic       = "deny"
